[build]
  publish = "dist/"
  functions = 'functions/'

[[headers]]
  for = "/"
  [headers.values]
    X-Clacks-Overhead = "GNU Terry Pratchett"
  for = "/*"
  [headers.values]
    X-Clacks-Overhead = "GNU Terry Pratchett" 
  for = "/**/*"
  [headers.values]
    X-Clacks-Overhead = "GNU Terry Pratchett"   